DROP TABLE IF EXISTS TBL_COINDESK;

CREATE TABLE TBL_CONDESK(
  TIME VARCHAR(50) NOT NULL,
  disclaimer VARCHAR(50) NOT NULL,
  chartName VARCHAR(50) NOT NULL,
  bpi VARCHAR(50) NOT NULL,
  code VARCHAR(50) NOT NULL,
  symbol VARCHAR(50) NOT NULL,
  rate VARCHAR(50) NOT NULL,
  description VARCHAR(50) NOT NULL,
  rate_float VARCHAR(50) NOT NULL,
);
